---
- hosts: digitalocean
  tasks:
      - name: Setup SSH keys
        digital_ocean:
          state: present
          command: ssh
          name: fedora
          ssh_pub_key: $SSH_PUB_KEY
        register: ssh_key_id

      - debug:
          msg: "{{ ssh_key_id.ssh_key.id }}"
